### PR TITLE
Feature/add wait selector

### PR DESCRIPTION
**Pull request by thangman22**
Add wait selector for page that need Ajax request before response.

### CODE REVIEW

**Comment by PaulKinlan** [comment]
Thank you! 

I am not sure how this interplays with `waitUntil` in the `goto()` command.

If the intent is to dump the DOM as soon as the selector(s) is/are found, in which case we probably need to restructure this and change the way that we handle the navigation timing and not wait for the network to stop (i.e, when this argument is passed into the command line it will override the current behavior).

If the intent is to only dump the DOM to STDOUT if we match a criteria, then we might need to change the naming or clear up the documentation. Right now it looks like the code will error if no selector is found (after a timeout of 30s) - which might be ok.

**Comment by thangman22** [comment]
Let me check the error

**Comment by thangman22** [comment]
@PaulKinlan I'm open for renaming. Just push error handling for selector not found

**Comment by PaulKinlan** [comment]
Just as an FYI - I've refactored the runner logic and it will mean that this code is not merge-able. https://github.com/PaulKinlan/domcurl/commit/f4253976a9aa3f52bf835eab4a6c8bcabfd2d680

**Pull request closed without merging**
